
CREATE TABLE AUDIENCE_CONNECTOR_SEGMENTS (
  RUN_TIME TIMESTAMP_NTZ(9), 
  --IDENTIFIERS
  FIRST_NAME VARCHAR(50), 
  LAST_NAME VARCHAR(50), 
  TEL_NUMBER VARCHAR(50), 
  GENDER VARCHAR(50), 
  DOB TIMESTAMP_NTZ(9), 
  ZIP_CODE VARCHAR(50), 
  CITY VARCHAR(50), 
  COUNTRY VARCHAR(50), 
  EMAIL1 VARCHAR(100), 
  EMAIL2 VARCHAR(100), 
  EMAIL3 VARCHAR(100), 
  --SEGMENTS
  LAPSED_MOTOR VARCHAR(1), 
  LAPSED_HOME VARCHAR(1), 
  ACTIVE_MOTOR_QUOTE VARCHAR(1), 
  ACTIVE_HOME_QUOTE VARCHAR(1), 
  BABYBOOMER_MOTOR VARCHAR(1), 
  BABYBOOMER_HOME VARCHAR(1), 
  PWC_MOTOR VARCHAR(1), 
  PWC_HOME VARCHAR(1), 
  EXC_PWC_BB_MOTOR VARCHAR(1), 
  EXC_PWC_BB_HOME VARCHAR(1), 
  EQUITY_LEADS VARCHAR(1), 
  SAVINGS VARCHAR(1)
);
